### ISSUE TITLE
An exception of type 'System.Text.Json.JsonException'  on GetDeviceFeatures

### ISSUE THREAD

**Issue by sebwaks** [philipdaubmeier/GraphIoT#15]
Hi Philip 
First of all great work on that library specially for Viessmann API . However there is sthing wrong with serialization and schedule Type, have you seen that before 

```
Exception has occurred: CLR/System.Text.Json.JsonException
An exception of type 'System.Text.Json.JsonException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The JSON value could not be converted to PhilipDaubmeier.ViessmannClient.Model.Features.Schedule.'
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonSerializer.HandleStartArray(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at PhilipDaubmeier.ViessmannClient.Network.ViessmannAuthBase.<CallViessmannApi>d__10`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PhilipDaubmeier.ViessmannClient.ViessmannPlatformClient.<GetDeviceFeatures>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at viessmantest.Program.<Main>d__0.MoveNext() in C:\Projects\viessmantest\Program.cs:line 28
```

Line which throws that is 

`var features = await client.GetDeviceFeatures(installationId, gatewayId);`

Have you seen that before ? 

Im just testing connector 

```
ViessmannAuth viessmannAuth = new ViessmannAuth("sesecret", "secret");
var viessmannConnProvider = new ViessmannConnectionProvider<ViessmannPlatformClient>(viessmannAuth);
viessmannConnProvider.PlattformApiClientId="myclientid";
viessmannConnProvider.PlattformApiClientSecret="mysecret";

var client = new ViessmannPlatformClient(viessmannConnProvider);
var installationId = (await client.GetInstallations()).First().LongId;
Console.WriteLine(installationId);
var gatewayId = (await client.GetGateways(installationId)).First().LongId;
Console.WriteLine(gatewayId);
var devices = (await client.GetDevices(installationId, gatewayId)).ToList();
var features = await client.GetDeviceFeatures(installationId, gatewayId);
```

**Comment by philipdaubmeier** [comment]
Hi, thanks for your interest and for reporting. Actually, I didn't see that error before. It seems like your installation has features that mine doesn't have and that leads to the json parsing error as it doesn't expect a specific format of your schedule.

Can you (privately) send me the raw json data of your installation, so I can have a look at it and fix it in the library?

I explained the easiest way of getting the raw json here: [GraphIoT #3](https://github.com/philipdaubmeier/GraphIoT/issues/3#issuecomment-609420973)

**Comment by philipdaubmeier** [comment]
Thanks for the raw data you sent me, I could now reproduce the bug - looking into fixing it now.

**Comment by philipdaubmeier** [comment]
Fixed with #16, published as new nuget package: [ViessmannClient 1.8.2](https://www.nuget.org/packages/PhilipDaubmeier.ViessmannClient/1.8.2)

**Comment by sebwaks** [comment]
Superb , fix works

**Comment by philipdaubmeier** [comment]
Good to hear that it works!

By the way: I added all missing features that your installation has, but mine didn't - quite a few. There is no convenience method for them, but you can access them by the `Name` enum value like so:

``` csharp
var props = features.GetRawFeatureByName((FeatureName)FeatureName.Name.VentilationOperatingModesActive);
var ventilationModesActive = props.Properties?.Active?.Value;
```

Here you can see the added features for ventilation, cooling and your heat pump: [`FeatureName.cs` in Changeset 456501f](https://github.com/philipdaubmeier/GraphIoT/commit/456501fac548150912b539d89c90491df7ae3db1#diff-8de39a6f588730ea1297ce3501f6d2f5)
