### ISSUE TITLE
URI in AuthState is empty when running simple example from README

### ISSUE THREAD

**Issue by mikkelrj** [philipdaubmeier/GraphIoT#17]
I get a 'Login retry unsucessful, API response could not be parsed, see inner exception.' exception when running the simple test snippet given in the README for WeConnect:

```
var auth = new WeConnectAuth("<omitted>", "<omitted>");
using var connectionProvider = new WeConnectConnectionProvider(auth);

var client = new WeConnectPortalClient(connectionProvider);

foreach (var vehicle in await client.GetVehicleList())
    Console.WriteLine($"VIN: {vehicle.Vin} name: {vehicle.Name}");
```

I tested this with the NuGet package PhilipDaubmeier.WeConnectClient version 1.1.0.

The root cause is an 'Could not authenticate, see inner exception for details' exception with stack trace:
```
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<Authenticate>d__15.MoveNext()
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<RequestApi>d__13`1.MoveNext()
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<RequestApi>d__12.MoveNext()
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<CallApiNoRetry>d__11`2.MoveNext()
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<CallApi>d__10`2.MoveNext()
```

Inner exception 'Invalid URI: The URI is empty.' with stack trace:
```
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at PhilipDaubmeier.WeConnectClient.Model.Auth.AuthState.get_BaseUri()
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.ClearCookies(AuthState state)
   at PhilipDaubmeier.WeConnectClient.Network.WeConnectAuthBase.<Authenticate>d__15.MoveNext()
```

Seems the AuthState BaseUri is never being set.

**Comment by philipdaubmeier** [comment]
Yes this is a known issue - the old WeConnect API no longer exists, there was a breaking change on Volkswagen side. The library would have to be rewritten completely, which I currently do not have the time for.
